steps:
 # build the container image
- name: 'build docker'
  args: ['build', 't', 'gcr.io/$PROJECT_ID/gcpdevops','.']
# push container image
- name: 'push docker'
- args: ["push",'gcr.io/$PROJECT_ID/gcpdevops'] 
# deploy container image to GKE
- name: 'deploy to GKE'
  args: 
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-central1-c
  - --cluster=gke-gcp-devops
  - --namespace=gcp-devops-prod  